# Practice set for the Coding Interview Refresher, grouped by the book's patterns.
# Each row: (number, title, slug, difficulty, sources, premium)
# sources: n = NeetCode 150, g = Grind 75, b = book's own pick
P = [
("prefix-sums", "Hash maps and prefix sums", "Chapter 2 · video pattern 1",
 "Pairs, counts and 'have I seen this?' are a hash map. Sums of contiguous runs, especially with negative numbers: prefix sums plus a map of prefix counts.", [
 (217,"Contains Duplicate","contains-duplicate","E","ng"),
 (242,"Valid Anagram","valid-anagram","E","ng"),
 (1,"Two Sum","two-sum","E","ngb"),
 (383,"Ransom Note","ransom-note","E","g"),
 (169,"Majority Element","majority-element","E","g"),
 (409,"Longest Palindrome","longest-palindrome","E","g"),
 (49,"Group Anagrams","group-anagrams","M","nb"),
 (271,"Encode and Decode Strings","encode-and-decode-strings","M","n","premium"),
 (238,"Product of Array Except Self","product-of-array-except-self","M","ngb"),
 (36,"Valid Sudoku","valid-sudoku","M","n"),
 (128,"Longest Consecutive Sequence","longest-consecutive-sequence","M","nb"),
 (560,"Subarray Sum Equals K","subarray-sum-equals-k","M","b"),
 (525,"Contiguous Array","contiguous-array","M","b"),
]),
("two-pointers-windows", "Two pointers and sliding windows", "Chapter 3 · video pattern 2",
 "Sorted input and a pair or triple with a target: opposite-end pointers. Longest or shortest contiguous piece with a property, where a bigger piece can only be worse: sliding window with a count map.", [
 (125,"Valid Palindrome","valid-palindrome","E","ng"),
 (121,"Best Time to Buy and Sell Stock","best-time-to-buy-and-sell-stock","E","ng"),
 (167,"Two Sum II - Input Array Is Sorted","two-sum-ii-input-array-is-sorted","M","n"),
 (75,"Sort Colors","sort-colors","M","g"),
 (15,"3Sum","3sum","M","ngb"),
 (11,"Container With Most Water","container-with-most-water","M","ngb"),
 (3,"Longest Substring Without Repeating Characters","longest-substring-without-repeating-characters","M","ngb"),
 (424,"Longest Repeating Character Replacement","longest-repeating-character-replacement","M","nb"),
 (567,"Permutation in String","permutation-in-string","M","n"),
 (438,"Find All Anagrams in a String","find-all-anagrams-in-a-string","M","g"),
 (76,"Minimum Window Substring","minimum-window-substring","H","ngb"),
 (42,"Trapping Rain Water","trapping-rain-water","H","ngb"),
 (992,"Subarrays with K Different Integers","subarrays-with-k-different-integers","H","b"),
]),
("binary-search", "Binary search, including on the answer", "Chapter 4 · video pattern 3",
 "Sorted data, or 'smallest x that works', 'minimise the maximum', 'least time to finish' with a cheap check that is false-then-true: binary search, on the array or on the answer itself.", [
 (704,"Binary Search","binary-search","E","ngb"),
 (278,"First Bad Version","first-bad-version","E","g"),
 (74,"Search a 2D Matrix","search-a-2d-matrix","M","n"),
 (153,"Find Minimum in Rotated Sorted Array","find-minimum-in-rotated-sorted-array","M","nb"),
 (33,"Search in Rotated Sorted Array","search-in-rotated-sorted-array","M","ngb"),
 (875,"Koko Eating Bananas","koko-eating-bananas","M","nb"),
 (1011,"Capacity To Ship Packages Within D Days","capacity-to-ship-packages-within-d-days","M","b"),
 (981,"Time Based Key-Value Store","time-based-key-value-store","M","ngb"),
 (4,"Median of Two Sorted Arrays","median-of-two-sorted-arrays","H","n"),
 (410,"Split Array Largest Sum","split-array-largest-sum","H","b"),
]),
("stacks", "Stacks, monotonic stacks and deques", "Chapter 5 · video pattern 4",
 "Nested brackets and 'undo the last thing': a plain stack. Next greater, previous smaller, 'how long until', spans, histograms: a stack of things still waiting, where each newcomer resolves what it beats. Window max or min: a monotonic deque.", [
 (20,"Valid Parentheses","valid-parentheses","E","ngb"),
 (232,"Implement Queue using Stacks","implement-queue-using-stacks","E","g"),
 (155,"Min Stack","min-stack","M","ngb"),
 (150,"Evaluate Reverse Polish Notation","evaluate-reverse-polish-notation","M","ng"),
 (739,"Daily Temperatures","daily-temperatures","M","nb"),
 (901,"Online Stock Span","online-stock-span","M","b"),
 (853,"Car Fleet","car-fleet","M","n"),
 (394,"Decode String","decode-string","M","b"),
 (239,"Sliding Window Maximum","sliding-window-maximum","H","nb"),
 (84,"Largest Rectangle in Histogram","largest-rectangle-in-histogram","H","ngb"),
 (224,"Basic Calculator","basic-calculator","H","g"),
]),
("linked-lists", "Linked lists", "Chapter 6",
 "A dummy head removes the empty-list special case. Fast and slow pointers find the middle and detect cycles. Reversal is three pointers, in place. Harder ones combine a list with a hash map or a heap.", [
 (206,"Reverse Linked List","reverse-linked-list","E","ngb"),
 (21,"Merge Two Sorted Lists","merge-two-sorted-lists","E","ngb"),
 (141,"Linked List Cycle","linked-list-cycle","E","ng"),
 (876,"Middle of the Linked List","middle-of-the-linked-list","E","g"),
 (142,"Linked List Cycle II","linked-list-cycle-ii","M","b"),
 (143,"Reorder List","reorder-list","M","nb"),
 (19,"Remove Nth Node From End of List","remove-nth-node-from-end-of-list","M","nb"),
 (138,"Copy List with Random Pointer","copy-list-with-random-pointer","M","nb"),
 (2,"Add Two Numbers","add-two-numbers","M","n"),
 (287,"Find the Duplicate Number","find-the-duplicate-number","M","n"),
 (25,"Reverse Nodes in k-Group","reverse-nodes-in-k-group","H","nb"),
]),
("trees", "Trees", "Chapter 7",
 "Most tree questions are one recursive function that returns a value for the subtree (height, sum, validity) while updating a running best. Level questions: BFS with a queue, one level per loop. BST questions: in-order is sorted order.", [
 (226,"Invert Binary Tree","invert-binary-tree","E","ng"),
 (104,"Maximum Depth of Binary Tree","maximum-depth-of-binary-tree","E","ngb"),
 (543,"Diameter of Binary Tree","diameter-of-binary-tree","E","ngb"),
 (110,"Balanced Binary Tree","balanced-binary-tree","E","ng"),
 (100,"Same Tree","same-tree","E","n"),
 (572,"Subtree of Another Tree","subtree-of-another-tree","E","n"),
 (235,"Lowest Common Ancestor of a Binary Search Tree","lowest-common-ancestor-of-a-binary-search-tree","M","ng"),
 (236,"Lowest Common Ancestor of a Binary Tree","lowest-common-ancestor-of-a-binary-tree","M","gb"),
 (102,"Binary Tree Level Order Traversal","binary-tree-level-order-traversal","M","ngb"),
 (199,"Binary Tree Right Side View","binary-tree-right-side-view","M","ng"),
 (1448,"Count Good Nodes in Binary Tree","count-good-nodes-in-binary-tree","M","n"),
 (98,"Validate Binary Search Tree","validate-binary-search-tree","M","ngb"),
 (230,"Kth Smallest Element in a BST","kth-smallest-element-in-a-bst","M","ngb"),
 (105,"Construct Binary Tree from Preorder and Inorder Traversal","construct-binary-tree-from-preorder-and-inorder-traversal","M","ng"),
 (124,"Binary Tree Maximum Path Sum","binary-tree-maximum-path-sum","H","nb"),
 (297,"Serialize and Deserialize Binary Tree","serialize-and-deserialize-binary-tree","H","ngb"),
]),
("heaps", "Heaps and top-k", "Chapter 8",
 "Top k, k-th largest, k closest: a heap of size k, O(n log k). Merge k sorted streams: a heap of heads. Running median: two heaps. Scheduling with 'most frequent first': a max-heap.", [
 (703,"Kth Largest Element in a Stream","kth-largest-element-in-a-stream","E","n"),
 (1046,"Last Stone Weight","last-stone-weight","E","n"),
 (973,"K Closest Points to Origin","k-closest-points-to-origin","M","ngb"),
 (215,"Kth Largest Element in an Array","kth-largest-element-in-an-array","M","nb"),
 (347,"Top K Frequent Elements","top-k-frequent-elements","M","nb"),
 (621,"Task Scheduler","task-scheduler","M","ngb"),
 (355,"Design Twitter","design-twitter","M","n"),
 (23,"Merge k Sorted Lists","merge-k-sorted-lists","H","ngb"),
 (295,"Find Median from Data Stream","find-median-from-data-stream","H","ngb"),
]),
("intervals", "Intervals and sweep lines", "Chapter 9",
 "Sort by start, then walk once: merge when the next start is inside the current end, or count removals. 'Maximum concurrent' or 'rooms needed': a sweep line of +1 and -1 events, or a min-heap of end times.", [
 (252,"Meeting Rooms","meeting-rooms","E","n","premium"),
 (57,"Insert Interval","insert-interval","M","ngb"),
 (56,"Merge Intervals","merge-intervals","M","ngb"),
 (435,"Non-overlapping Intervals","non-overlapping-intervals","M","nb"),
 (452,"Minimum Number of Arrows to Burst Balloons","minimum-number-of-arrows-to-burst-balloons","M","b"),
 (986,"Interval List Intersections","interval-list-intersections","M","b"),
 (1094,"Car Pooling","car-pooling","M","b"),
 (253,"Meeting Rooms II","meeting-rooms-ii","M","nb","premium"),
 (1851,"Minimum Interval to Include Each Query","minimum-interval-to-include-each-query","H","n"),
 (1235,"Maximum Profit in Job Scheduling","maximum-profit-in-job-scheduling","H","g"),
]),
("graphs", "Graphs", "Chapter 10",
 "Grids and adjacency lists are the same thing. Shortest path with unit steps: BFS. Components and reachability: DFS or union-find. Prerequisites and ordering: Kahn's topological sort. Weighted shortest path: Dijkstra with a heap.", [
 (733,"Flood Fill","flood-fill","E","g"),
 (200,"Number of Islands","number-of-islands","M","ngb"),
 (695,"Max Area of Island","max-area-of-island","M","n"),
 (133,"Clone Graph","clone-graph","M","ngb"),
 (542,"01 Matrix","01-matrix","M","g"),
 (994,"Rotting Oranges","rotting-oranges","M","ngb"),
 (417,"Pacific Atlantic Water Flow","pacific-atlantic-water-flow","M","nb"),
 (130,"Surrounded Regions","surrounded-regions","M","n"),
 (286,"Walls and Gates","walls-and-gates","M","n","premium"),
 (207,"Course Schedule","course-schedule","M","ng"),
 (210,"Course Schedule II","course-schedule-ii","M","nb"),
 (310,"Minimum Height Trees","minimum-height-trees","M","g"),
 (684,"Redundant Connection","redundant-connection","M","nb"),
 (323,"Number of Connected Components in an Undirected Graph","number-of-connected-components-in-an-undirected-graph","M","n","premium"),
 (261,"Graph Valid Tree","graph-valid-tree","M","n","premium"),
 (721,"Accounts Merge","accounts-merge","M","gb"),
 (743,"Network Delay Time","network-delay-time","M","nb"),
 (1584,"Min Cost to Connect All Points","min-cost-to-connect-all-points","M","n"),
 (787,"Cheapest Flights Within K Stops","cheapest-flights-within-k-stops","M","n"),
 (332,"Reconstruct Itinerary","reconstruct-itinerary","H","n"),
 (778,"Swim in Rising Water","swim-in-rising-water","H","n"),
 (269,"Alien Dictionary","alien-dictionary","H","n","premium"),
 (127,"Word Ladder","word-ladder","H","ngb"),
]),
("backtracking", "Backtracking", "Chapter 11",
 "'All subsets', 'all permutations', 'all combinations that sum to', 'place things on a board': choose, recurse, undo. Sort first to skip duplicates, and prune as soon as a partial answer cannot work.", [
 (78,"Subsets","subsets","M","ngb"),
 (39,"Combination Sum","combination-sum","M","ngb"),
 (46,"Permutations","permutations","M","ngb"),
 (90,"Subsets II","subsets-ii","M","nb"),
 (40,"Combination Sum II","combination-sum-ii","M","n"),
 (22,"Generate Parentheses","generate-parentheses","M","n"),
 (17,"Letter Combinations of a Phone Number","letter-combinations-of-a-phone-number","M","ngb"),
 (79,"Word Search","word-search","M","ngb"),
 (131,"Palindrome Partitioning","palindrome-partitioning","M","nb"),
 (51,"N-Queens","n-queens","H","nb"),
]),
("dynamic-programming", "Dynamic programming", "Chapter 12",
 "Count the ways, or find the best, over a sequence of choices where the same subproblem comes back: name the state, write the recurrence from the last decision, then memoise or fill a table. Families: 1-D steps, knapsack, two sequences, intervals.", [
 (70,"Climbing Stairs","climbing-stairs","E","ngb"),
 (746,"Min Cost Climbing Stairs","min-cost-climbing-stairs","E","n"),
 (198,"House Robber","house-robber","M","nb"),
 (213,"House Robber II","house-robber-ii","M","n"),
 (5,"Longest Palindromic Substring","longest-palindromic-substring","M","ng"),
 (647,"Palindromic Substrings","palindromic-substrings","M","n"),
 (91,"Decode Ways","decode-ways","M","n"),
 (322,"Coin Change","coin-change","M","ngb"),
 (152,"Maximum Product Subarray","maximum-product-subarray","M","n"),
 (139,"Word Break","word-break","M","ngb"),
 (300,"Longest Increasing Subsequence","longest-increasing-subsequence","M","nb"),
 (416,"Partition Equal Subset Sum","partition-equal-subset-sum","M","ngb"),
 (62,"Unique Paths","unique-paths","M","ngb"),
 (1143,"Longest Common Subsequence","longest-common-subsequence","M","nb"),
 (309,"Best Time to Buy and Sell Stock with Cooldown","best-time-to-buy-and-sell-stock-with-cooldown","M","nb"),
 (518,"Coin Change II","coin-change-ii","M","n"),
 (494,"Target Sum","target-sum","M","n"),
 (97,"Interleaving String","interleaving-string","M","n"),
 (72,"Edit Distance","edit-distance","M","nb"),
 (329,"Longest Increasing Path in a Matrix","longest-increasing-path-in-a-matrix","H","n"),
 (115,"Distinct Subsequences","distinct-subsequences","H","n"),
 (312,"Burst Balloons","burst-balloons","H","n"),
 (10,"Regular Expression Matching","regular-expression-matching","H","n"),
]),
("greedy-tries-bits-design", "Greedy, tries, bits and design", "Chapter 13",
 "Greedy: a local choice that is provably safe, usually after sorting. Tries: many words, prefix queries. Bits: XOR cancels pairs, n & (n-1) drops the lowest bit. Design: 'O(1) for every operation' is a hash map plus a linked list or an array.", [
 (53,"Maximum Subarray","maximum-subarray","M","ng"),
 (55,"Jump Game","jump-game","M","nb"),
 (45,"Jump Game II","jump-game-ii","M","n"),
 (134,"Gas Station","gas-station","M","nb"),
 (846,"Hand of Straights","hand-of-straights","M","n"),
 (1899,"Merge Triplets to Form Target Triplet","merge-triplets-to-form-target-triplet","M","n"),
 (763,"Partition Labels","partition-labels","M","nb"),
 (678,"Valid Parenthesis String","valid-parenthesis-string","M","n"),
 (208,"Implement Trie (Prefix Tree)","implement-trie-prefix-tree","M","ngb"),
 (211,"Design Add and Search Words Data Structure","design-add-and-search-words-data-structure","M","n"),
 (212,"Word Search II","word-search-ii","H","nb"),
 (136,"Single Number","single-number","E","nb"),
 (191,"Number of 1 Bits","number-of-1-bits","E","n"),
 (338,"Counting Bits","counting-bits","E","nb"),
 (190,"Reverse Bits","reverse-bits","E","n"),
 (268,"Missing Number","missing-number","E","n"),
 (67,"Add Binary","add-binary","E","g"),
 (371,"Sum of Two Integers","sum-of-two-integers","M","n"),
 (7,"Reverse Integer","reverse-integer","M","n"),
 (48,"Rotate Image","rotate-image","M","nb"),
 (54,"Spiral Matrix","spiral-matrix","M","ngb"),
 (73,"Set Matrix Zeroes","set-matrix-zeroes","M","n"),
 (202,"Happy Number","happy-number","E","n"),
 (66,"Plus One","plus-one","E","n"),
 (50,"Pow(x, n)","powx-n","M","n"),
 (43,"Multiply Strings","multiply-strings","M","n"),
 (2013,"Detect Squares","detect-squares","M","n"),
 (8,"String to Integer (atoi)","string-to-integer-atoi","M","g"),
 (146,"LRU Cache","lru-cache","M","ngb"),
 (380,"Insert Delete GetRandom O(1)","insert-delete-getrandom-o1","M","b"),
]),
]
